### ISSUE TITLE
cb is not a function when successful completPasswordReset

### ISSUE THREAD

**Issue by vrghost242** [deitch/activator#48]
Think I have followed the instructions, or at least as I understood them, and have gotten almost everything working. However, when I call the completePasswordReset, and after the password is updated, I get the following issue:

```
/Users/bengtbjorkberg/WebstormProjects/unbrandme.https/node_modules/activator/lib/activator.js:226
				cb(null);
				^

TypeError: cb is not a function
    at async.waterfall.code (/Users/bengtbjorkberg/WebstormProjects/unbrandme.https/node_modules/activator/lib/activator.js:226:5)
    at fn (/Users/bengtbjorkberg/WebstormProjects/unbrandme.https/node_modules/activator/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/Users/bengtbjorkberg/WebstormProjects/unbrandme.https/node_modules/activator/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The route called looks as follows:
router.put('/request/reset/password/:user' ,activator.completePasswordReset)

**Comment by vrghost242** [comment]
Not certain why, but I get the above error message, and it must be limited to my system (otherwise everyone SHOULD have it), but if you have messed it up the same way as I have, the below fix around line 226 in ./lib/activator.js seems to do the trick (just return null instead of cv null. 


```
		function (res,cb) {
			if (sendPasswordResetComplete) {
				mailer("passwordresetcomplete",req.lang||"en_US",{email:user.email,id:id,password:newpass,request:req},from,user.email,attachments.passwordresetcomplete,cb);
			} else {
				return(null)
				//cb(null);
			}
		}
```

**Comment by deitch** [comment]
Thanks for putting in a proposed fix, but, yes, if it were an issue, everyone would get tripped up and the tests would fail.

Based on your proposed change, I suspect that your `setPassword()` function is calling back without passing a parameter. Based on LL201-210 in the README, it should be passing back a `res` and a `cb`. Especially look at the following from L210:

````
* `callback`: the callback function that `user.activate()` should call when complete. Has the signature `callback(err)`. If the save is successful, `err` **must** be `null` (not `undefined`).
````

What is your original code that is tripping it up? More specifically, when you call the following:

````javascript
activator = require('activator');
activator.init(config);
````

What is the `config` you pass to `init()`, and specially, what is the `user` property, and very specifically what is its `user.setPassword()` function?

**Comment by vrghost242** [comment]
First question first, this is the config
`activator.init({user: activatorCfg, transport: activatorCfg.smtpUrl , from: activatorCfg.fromEmail, templates: activatorCfg.templatesDir, signkey: activatorCfg.signkey, attachments: activatorCfg.attachments});`

activatorCfg is a module, looks as follows:
 ```
//Lets load some other useful bits
var bcrypt = require('bcrypt-nodejs');
var dbconfig = require('./database');
var mgUser = require('../schemas/user.js');

var bunyan = require('bunyan');
var cfgBunyan = require('./bunyan')
var log = bunyan.createLogger({name: cfgBunyan.name, subsystem: "ACTIVATOR"});
var fs = require('fs');

//activator.init({
    //user: mgUser,
  //  id: "email",
    //transport: unbrandTransporter,
   // from:"support@unbrand.me",
   // templates: "/Users/bengtbjorkberg/WebstormProjects/unbrandme.https/mailtemplates",
   // signkey: "C0ca1n1sB4d"
//});



//sqlConnection.query('USE ' + dbconfig.sqlDatabase);
module.exports = {

   smtpUrl: nodemailerCfg.unbrandTransporter,
    fromEmail: nodemailerCfg.unbrandSupport,
    signkey: "Notputtingthathere",
    //id: "local.email",
    templatesDir: "./mailtemplates",
    attachments_default: [
        {filename: './img/facebook.png',
            content: fs.createReadStream('./mailtemplates/img/facebook.png')},
        {filename: './img/twitter.png',
            path: './mailtemplates/img/twitter.png'},
        {filename: './img/linkedin.png',
            path: './mailtemplates/img/linkedin.png'}
    ],
    attachments: { passwordreset:
        [ { filename: 'img/facebook.png',
            path: './mailtemplates/img/facebook.png',
            cid: 'a1pj5lkeomzl9z03506s6pqfr' },
            { filename: 'img/twitter.png',
                path: './mailtemplates/img/twitter.png',
                cid: '6xpmu3y0cqo2z3pdcsvloez5mi' },
            { filename: 'img/linkedin.png',
                path: './mailtemplates/img/linkedin.png',
                cid: '4ygxxo05k44ubahgqunlsdcxr' },
            { filename: 'img/logo.png',
                path: './mailtemplates/img/868bb7f710da41479f230972c564ecd5.png',
                cid: '868bb7f710da41479f230972c564ecd5' } ],
        activate:
            [ { filename: 'img/facebook.png',
                path: './mailtemplates/img/facebook.png',
                cid: 'a1pj5lkeomzl9z03506s6pqfr' },
                { filename: 'img/twitter.png',
                    path: './mailtemplates/img/twitter.png',
                    cid: '6xpmu3y0cqo2z3pdcsvloez5mi' },
                { filename: 'img/linkedin.png',
                    path: './mailtemplates/img/linkedin.png',
                    cid: '4ygxxo05k44ubahgqunlsdcxr' },
                { filename: 'img/logo.png',
                    path: './mailtemplates/img/868bb7f710da41479f230972c564ecd5.png',
                    cid: '868bb7f710da41479f230972c564ecd5' } ]
    },
    find: function(id, callback){
        var email = id;
        if ( email.search("@") === -1 ) {
            log.info("Activator find request for _id " + email);
            var searchCriteria = { '_id': email};
        } else {
            log.info("Activator find request for email " + email);
            var searchCriteria = { 'local.email': email};
        }
        mgUser.findOne( searchCriteria , function(err, user){
            if(err){
                log.error("Failed to retrieve data for user " + email+ " error: ",err);
                callback(err, null)
            } else if(!user) {
                log.info("No user found for " + email)
                callback("NO_USER", "");
            } else {
                //console.log(user);
                var retData = {
                    id: user._id,
                    email: user.local.email,
                    //activation_code: user.local.activation_code,
                    //password_reset_code: user.local.password_reset_code,
                    //password_reset_time: user.local.password_reset_time,
                }
                console.log(retData)
                callback(null, retData)

            }
        })
    },
    activate: function(id,callback){
        mgUser.findById(id, function(err, user){
            if(err){
                log.error("Failed to retrieve data for user " + id+ " error: ",err);
                callback(err, null)
            } else if(!user) {
                log.info("No user found for " + id)
                callback("NO_USER", "");
            } else {
                //log.info("User found " + user.alias)
                user.local.activated = true;

                user.save( function (err,doc){
                    if(err){
                        log.error(err)
                        callback(err);
                    } else {
                        log.info("User activated, email " + user.local.email);
                        callback(null);
                    }
                })
//                callback(null, retData)

            }
        })
    },
    setPassword: function(id,password,callback){
        log.info("Was asked to reset password for " + id );
        mgUser.findById(id, function(err, user){
            if(err){
                log.error("Failed to retrieve data for user " + id+ " error: ",err);
                callback(err, null)
            } else if(!user) {
                log.info("No user found for " + id)
                callback("NO_USER", "");
            } else {
                //log.info("User found " + user.alias)
                user.local.password = user.generateHash(password);;

                user.save( function (err,doc){
                    if(err){
                        log.error(err)
                        callback(err);
                    } else {
                        log.info("User password updated for " + user.local.email);
                        callback(null);
                    }
                })
//                callback(null, retData)

            }
        })

    },
    save: function(id, data, callback) {
        log.warn("UNEXPECTED EXECUTION: Saving information for " + id, data)
        mgUser.findOne({ 'local.email': email}, function(err, user) {
            if (err) {
                log.error("Failed to retrieve data for user " + email + " error: ", err);
                callback(err, null)
            } else if (!user) {
                log.info("No user found for " + email)
                callback("NO_USER", "");
            } else {
                log.info(data);
                user.local = data;
                user.save(function (err) {
                    if (err) {
                        callback(err, null)
                    } else {
                        callback(null, "DONE")
                    }
                })
            }
        })
    }

}
```

Would setPassword be send res?
According to the documentation, I thought it would only get id, password and callback?

**Comment by deitch** [comment]
Yeah look. On some you do callbaxk(err,retreats) and on other callback(err); 

Inconsistent. It needs the payloads.

**Comment by vrghost242** [comment]
Spot on. returning (null, "Some message") for success works a treat it seems.

**Comment by deitch** [comment]
:-)
